export const TRADES_WITH_ICONS = [
  { name: "Electrician", icon: "⚡" },
  { name: "Plumber", icon: "🔧" },
  { name: "Painter", icon: "🎨" },
  { name: "Carpenter", icon: "🪚" },
  { name: "Mechanic", icon: "🚗" },
  { name: "Cleaner", icon: "🧹" },
  { name: "Gardener", icon: "🌱" },
  { name: "Cook", icon: "🍳" },
  { name: "Delivery", icon: "📦" },
  { name: "Technician", icon: "💻" },
  { name: "Mason", icon: "🧱" },
  { name: "Solar Technician", icon: "☀️" },
  { name: "Welder", icon: "👨‍🏭" },
  { name: "AC Technician", icon: "❄️" },
  { name: "Drone Operator", icon: "🛸" },
  { name: "Video Editor", icon: "🎬" },
  { name: "App Developer", icon: "📱" },
  { name: "Tutor", icon: "📚" },
  { name: "Photographer", icon: "📷" },
  { name: "Tailor", icon: "🪡" },
  { name: "Driver", icon: "🚛" },
  { name: "Security Guard", icon: "🛡️" },
  { name: "Beautician", icon: "💄" },
  { name: "Data Entry", icon: "⌨️" }
];

export const TRADES = TRADES_WITH_ICONS.map(t => t.name);

export const STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
];

export const MOCK_WORKERS = [
  {
    uid: "w1",
    displayName: "Ramesh Kumar",
    fullName: "Ramesh Kumar",
    trade: "Mason",
    location: { city: "Mysuru", district: "Mysuru", state: "Karnataka", lat: 12.2958, lng: 76.6394 },
    dakshScore: 85,
    wage: 800,
    verified: true,
    isVerified: true,
    skills: ["Bricklaying", "Plastering", "Concrete Work"],
    experience: 12,
    email: "ramesh@example.com",
    phoneNumber: "9876543210",
    role: "worker",
    photo: "https://picsum.photos/seed/w1/200",
    bio: "Expert mason with 12 years of experience in residential construction.",
    badges: ["Top Rated", "Verified"],
    createdAt: new Date().toISOString()
  },
  {
    uid: "w2",
    displayName: "Suresh Yadav",
    fullName: "Suresh Yadav",
    trade: "Electrician",
    location: { city: "Varanasi", district: "Varanasi", state: "Uttar Pradesh", lat: 25.3176, lng: 82.9739 },
    dakshScore: 72,
    wage: 900,
    verified: true,
    isVerified: true,
    skills: ["Wiring", "Repair", "Maintenance"],
    experience: 8,
    email: "suresh@example.com",
    phoneNumber: "9876543211",
    role: "worker",
    photo: "https://picsum.photos/seed/w2/200",
    bio: "Certified electrician specializing in home wiring and industrial maintenance.",
    badges: ["Verified"],
    createdAt: new Date().toISOString()
  },
  {
    uid: "w3",
    displayName: "Priya Devi",
    fullName: "Priya Devi",
    trade: "Painter",
    location: { city: "Nashik", district: "Nashik", state: "Maharashtra", lat: 19.9975, lng: 73.7898 },
    dakshScore: 91,
    wage: 750,
    verified: true,
    isVerified: true,
    skills: ["Interior", "Exterior", "Texture"],
    experience: 10,
    email: "priya@example.com",
    phoneNumber: "9876543212",
    role: "worker",
    photo: "https://picsum.photos/seed/w3/200",
    bio: "Professional painter with an eye for detail and texture work.",
    badges: ["Top Rated", "Verified"],
    createdAt: new Date().toISOString()
  },
  {
    uid: "w4",
    displayName: "Mohan Lal",
    fullName: "Mohan Lal",
    trade: "Plumber",
    location: { city: "Jaipur", district: "Jaipur", state: "Rajasthan", lat: 26.9124, lng: 75.7873 },
    dakshScore: 65,
    wage: 850,
    verified: true,
    isVerified: true,
    skills: ["Pipe Fitting", "Drainage", "Installation"],
    experience: 15,
    email: "mohan@example.com",
    phoneNumber: "9876543213",
    role: "worker",
    photo: "https://picsum.photos/seed/w4/200",
    bio: "Reliable plumber with extensive experience in drainage and pipe installations.",
    badges: ["Verified"],
    createdAt: new Date().toISOString()
  },
  {
    uid: "w5",
    displayName: "Arjun Singh",
    fullName: "Arjun Singh",
    trade: "Carpenter",
    location: { city: "Ludhiana", district: "Ludhiana", state: "Punjab", lat: 30.9010, lng: 75.8573 },
    dakshScore: 78,
    wage: 1000,
    verified: true,
    isVerified: true,
    skills: ["Furniture", "Woodwork", "Polishing"],
    experience: 20,
    email: "arjun@example.com",
    phoneNumber: "9876543214",
    role: "worker",
    photo: "https://picsum.photos/seed/w5/200",
    bio: "Master carpenter with 20 years of experience in furniture and fine woodwork.",
    badges: ["Expert", "Verified"],
    createdAt: new Date().toISOString()
  },
  {
    uid: "w6",
    displayName: "Kavita Bai",
    fullName: "Kavita Bai",
    trade: "Solar Technician",
    location: { city: "Pune", district: "Pune", state: "Maharashtra", lat: 18.5204, lng: 73.8567 },
    dakshScore: 88,
    wage: 1200,
    verified: true,
    isVerified: true,
    skills: ["Installation", "Maintenance", "Troubleshooting"],
    experience: 5,
    email: "kavita@example.com",
    phoneNumber: "9876543215",
    role: "worker",
    photo: "https://picsum.photos/seed/w6/200",
    bio: "Skilled solar technician focused on sustainable energy solutions.",
    badges: ["Verified"],
    createdAt: new Date().toISOString()
  }
];

export const MOCK_JOBS = [
  {
    id: "j1",
    title: "Residential Wiring Work",
    skillRequired: "Electrician",
    location: { city: "Bengaluru", district: "Bengaluru", state: "Karnataka", lat: 12.9716, lng: 77.5946 },
    wage: 950,
    duration: "3 days",
    employerName: "Aditya Sharma",
    status: "active",
    createdAt: new Date().toISOString()
  },
  {
    id: "j2",
    title: "3BHK Masonry Work",
    skillRequired: "Mason",
    location: { city: "Pune", district: "Pune", state: "Maharashtra", lat: 18.5204, lng: 73.8567 },
    wage: 1100,
    duration: "15 days",
    employerName: "Vikram Patil",
    status: "active",
    createdAt: new Date().toISOString()
  },
  {
    id: "j3",
    title: "Solar Panel Installation",
    skillRequired: "Solar Technician",
    location: { city: "Mysuru", district: "Mysuru", state: "Karnataka", lat: 12.2958, lng: 76.6394 },
    wage: 1200,
    duration: "2 days",
    employerName: "Sanjay Gowda",
    status: "active",
    createdAt: new Date().toISOString()
  },
  {
    id: "j4",
    title: "Plumbing Renovation",
    skillRequired: "Plumber",
    location: { city: "Mumbai", district: "Mumbai", state: "Maharashtra", lat: 19.0760, lng: 72.8777 },
    wage: 850,
    duration: "5 days",
    employerName: "Rajesh Mehta",
    status: "active",
    createdAt: new Date().toISOString()
  }
];
